### ISSUE TITLE
Activating AdGuard Tracking Protection Filter results in "too many filters" error

### ISSUE THREAD

**Issue by jblack14** [AdguardTeam/AdGuardForSafari#863]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.13

### Environment

```markdown
- OS: Big Sur, 11.7.8
- Safari version: 16.5.1 (16615.2.9.11.7, 16615)
```

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Issue Details

Steps to reproduce:
If I activate "AdGuard Tracking Protection Filter" (v 2.0.57.46) I get a warning "Too many filters enabled. Safari cannot use more than 150000 rules in one group."

Filters:
Other than that, the only other filter enabled in any section is:
AdGuard Base Filter (24008 rules used)

Rules:
AdGuard Privacy shows 33 rules used (w/o Tracking Protection Filter)
AdGuard Social shows 2 rules used
AdGuard Security shows 1 rule used
AdGuard Other shows 4 rules used
AdGuard Custom shows 1 rule used

### Expected Behavior

It works

### Actual Behavior

I get a warning "Too many filters enabled. Safari cannot use more than 150000 rules in one group."

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@jblack14 Please, check for the filters updates. 
This problem should be gone. Watch the https://github.com/AdguardTeam/AdGuardForSafari/issues/861 issue for details .
